version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.1.1
    ports:
      - "9092:9092"
    environment:
      # you need an /etc/hosts entry:
      #   192.168.99.100 kafka-etc-hosts-alias  # if you use docker-machine
      #   127.0.0.1 kafka-etc-hosts-alias       # if you use docker for mac
      KAFKA_ADVERTISED_HOST_NAME: kafka-etc-hosts-alias
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
